(maint) Add command line options to ticketmatch
puppetlabs/ticketmatch pull request #3
Opened 2018-04-10 21:14 UTC by speedofdark

2018-04-10 21:19 UTC, scottsolowild commented on ticketmatch.rb
> +  jira_project_fixed_version = ask('Enter JIRA fix version: ') {|q| q.default = "#{jira_project_name} #{git_to_rev}"}
This line is a bit long. I'd wrap by converting `{`/`}` to `do`/`end` with newlines for readability.

2018-04-10 21:21 UTC, mcdonaldseanp approved these changes
Other than Scott's readability comment, LGTM

2018-04-10 22:44 UTC, smcclellan requested changes
Can you squash all three of these commits into one? That way, in the commit history, there's no chance of the formatting fix or the README update being separated from the feature commit.

2018-04-10 22:53 UTC, speedofdark commented
Updated.

2018-04-11 17:10 UTC, smcclellan approved these changes

2018-04-11 17:24 UTC, scottsolowild commented
Just thought of this; might be good to add a `non-interactive` (or something like that) flag, so that if a pipeline misses a flag it won't stall indefinitely waiting for user input?

2018-04-11 17:35 UTC, speedofdark commented
At the moment, it prompts for anything you omit on the command line. Will do some research and come back to you.

2018-04-11 20:14 UTC, smcclellan approved these changes

2018-04-11 20:15 UTC, merged